network/config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include("django.contrib.auth.urls")),

    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

network/posts/urls.py
from django.urls import path
from .views import PostView, GroupPostView, SearchView
app_name = 'posts'

urlpatterns = [

    path('', PostView.as_view(), name='index'),
    path('search/', SearchView.as_view(), name='search_post'),
    path('group/<slug>/', GroupPostView.as_view(), name='group_post'),


]

network/users/urls.py
from django.urls import path
from .views import SignUp, ContactView
app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('contact/', ContactView.as_view(), name='contact'),



]

network/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True, related_name='groups')

    def __str__(self):
        title = self.text.split('.')[0]
        return title

    # def get_absolute_url(self):
    #     return reverse('post.index', kwargs={'id': self.id})

network/users/models.py
from django.db import models


class Contact(models.Model):
    """
    Сontact form with admin
    """
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    body = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    is_answered = models.BooleanField(default=False)

    def __str__(self):
        return self.subject

network/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import ModelForm
from .models import Contact


User = get_user_model()


class CreationForm(UserCreationForm):
    """
    Registration form
    """
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']


class ContactForm(ModelForm):
    """
    Сontact form with admin
    """
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'body']

network/posts/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Post, Group, User
from django.http import Http404


class PostView(View):
    """
    All posts
    """
    def get(self, request):
        posts = Post.objects.order_by('-pub_date')[:10]
        context = {'posts': posts}
        return render(request, 'posts/index.html', context)


class GroupPostView(View):
    """
    Groups posts
    """
    def get(self, request, slug):
        group = get_object_or_404(Group, slug=slug)
        print(group)
        posts = Post.objects.filter(group=group).order_by('-pub_date')
        context = {'posts': posts,
                   'group': group, }
        return render(request, 'posts/group.html', context)


class PostUser(View):
    """
    Post each authors
    """
    def get(self, request):
        posts = None
        keyword = 'утро'
        start_date = datetime.date(1854, 7, 7)
        end_date = datetime.date(1854, 7, 21)
        author = User.objects.get(username='leo')
        posts = Post.objects.filter(
                                    author=author,
                                    text__contains=keyword,
                                    pub_date__range=(start_date, end_date)
                                    )
        context = {'posts': posts}
        return render(request, 'posts/posts_user.html', context)


class SearchView(View):
    """
    Simple post search
    """
    def get(self, request):
        keyword = request.GET.get('q', None)
        if keyword:
            posts = Post.objects.select_related('author', 'group').filter(text__contains=keyword)
        else:
            posts = None
        context = {'posts': posts, 'keyword': keyword}
        return render(request, 'posts/search.html', context)

network/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CreationForm, ContactForm


class SignUp(CreateView):
    """
    Registration form
    """
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class ContactView(CreateView):
    """
    Сontact form with admin
    """
    form_class = ContactForm
    success_url = reverse_lazy('posts:index')
    template_name = 'contact_form.html'

network/posts/templates/posts/group.html
{% extends "base.html" %}

{% block title %}
    Записи сообщества "{{ group }}"

{% endblock %}

{% block header %}
    Записи сообщества "{{ group }}"
{% endblock %}

{% block content %}

        <p>
            Цитаты {{ group }}
        </p>

            {% for post in posts %}
                <h3>
                    Автор: {{ post.author.get_full_name }},
                    Дата публикации: {{ post.pub_date|date:"d M Y" }}
                </h3>
                <p>{{ post.text|linebreaksbr }}</p>
                {% if not forloop.last %}<hr>{% endif %}
                {% endfor %}

{% endblock %}

network/posts/templates/posts/index.html
{% extends "base.html" %}

{% block title %}
    Последние обновления на сайте
{% endblock %}

{% block header %}
    Последние записи
{% endblock %}

{% block content %}

    {% for post in posts %}
    <h3>
        Автор: {{ post.author.get_full_name }},
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

{% endblock %}

network/posts/templates/posts/search.html
{% extends "base.html" %}

{% block title %}
    Поиск
{% endblock %}

Поиск по записям<

{% block header %}

{% endblock %}

{% block content %}

  <div class="container">
    <h1>Поиск по записям</h1>

    <div class="card">
      <div class="card-body">

        <form class="form-inline" action="{% url 'posts:search_post' %}">
          <div class="form-row">
          <input name="q" class="form-control form-control-lg" type="search"
            placeholder="Поиск" {% if keyword %}value="{{ keyword }}"{% endif %}>
          <button class="btn" type="submit">Найти</button>
          </div>
        </form>
        </div>
      </div>

    <div class="container">
    {% for post in posts %}
    <strong>
        Автор: {{ post.author.get_full_name }},
        Дата публикации: {{ post.pub_date|date:"d M Y" }},
        Группа: {{ post.group.title }}
    </strong>
    <p>{{ post.text|linebreaksbr }}</p>
    <hr>
    {% endfor %}
    </div>

  </div>
{% endblock %}

network/templates/base.html
{% load static %}

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Network</title>

    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

    <!-- Если статика не грузиться -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
</head>
    {% include 'nav.html' %}
<body>

    <main>
        <div class="container">
            <h1>{% block header %}The Last Social Media{% endblock %}</h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html>

network/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Net</span>work</p>
    <img src="images/logo.jpg" alt="Network"/>
    <div id="copyright">© {{ year }}, все права защищены.</div>
</footer>

network/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Net</span>work</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'users:signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

network/templates/navbar.html
<nav class="navbar navbar-light navbar-expand-sm " style="background-color: #e3f2fd;">
<a class="navbar-brand" href="">Лого</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="">Тексты<span class="sr-only">(current)</span></a>
      </li>

      {% comment 'Пока подождет' %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'analysis:text_create_url' %}">Новый текст</a>
          </li>
          <li class="nav-item active">
             <a class="nav-link" href="{% url 'analysis:load_csv_url' %}">Загрузка CSV</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'analysis:work_url' %}">Работа с CSV</a>
          </li>
      {% endcomment %}

      </ul>
  </div>
</nav>

network/users/templates/contact_form.html
{% extends "base.html" %}

{% block title %}
    Форма
{% endblock %}

{% block header %}
    Форма запроса
{% endblock %}

{% block content %}

    <form class="form" method="POST" action="{% url 'users:contact' %}">
        <div class="form-control-lg">
            <div class="card" >
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Отправить">
                </div>
            </div>
        </div>
    </form>


{% endblock %}

network/users/templates/signup.html
{% extends 'base.html' %}

{% block title %}
    Зарегистрироваться
{% endblock %}

{% block header %}
    Регистрация
{% endblock %}

{% block content %}

<form class="form" method="POST"  action="{% url 'users:signup' %}">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
</form>

{% endblock %}